[package]
name = "embedded-sht3x"
version = "0.1.0"
authors = ["Ghislain MARY <ghislain@ghislainmary.fr>"]
repository = "https://gitlab.com/ghislainmary/embedded-sht3x"
license = "MIT OR Apache-2.0"
description = " Platform-agnostic Rust driver for the SHT3x temperature and humidity sensors."
readme = "README.md"
keywords = [
    "temperature",
    "humidity",
    "sensor",
    "sht3x",
    "sht30",
    "sht31",
    "sht35",
    "embedded-hal",
    "embedded-hal-driver",
    "no-std",
    "i2c",
]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://gitlab.com/ghislainmary/embedded-sht3x"
include = ["/**/*.rs", "/Cargo.toml", "/README.md"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.2"
crc = "3.0.1"
embedded-hal = "1.0.0"

[dev-dependencies]
embedded-hal-mock = { version = "0.10.0", default-features = false, features = [
    "eh1",
] }
linux-embedded-hal = "0.4.0"
