[package]
name = "embedded-sht3x"
version = "0.2.0"
authors = ["Ghislain MARY <ghislain@ghislainmary.fr>"]
repository = "https://github.com/ghismary/embedded-sht3x"
license = "MIT OR Apache-2.0"
description = " Platform-agnostic Rust driver for the SHT3x temperature and humidity sensors."
documentation = "https://docs.rs/embedded-sht3x/"
readme = "README.md"
keywords = ["temperature", "humidity", "sensor", "sht3x", "embedded-hal"]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://github.com/ghismary/embedded-sht3x"
include = ["/**/*.rs", "/Cargo.toml", "/README.md"]
edition = "2021"

[features]
default = []
async = []

[dependencies]
bitflags = "2.13"
crc = "3.4"
embedded-hal = "1.0"
embedded-hal-async = "1.0"
maybe-async-cfg = "0.2"
weather-utils = { version = "0.5", features = ["no-std"] }

[dev-dependencies]
embedded-hal-mock = { version = "0.11", default-features = false, features = [
    "eh1",
] }
heapless = "0.9"

[target.'cfg(target_os = "linux")'.dev-dependencies]
linux-embedded-hal = "0.4"
